[package]
name = "rek2_nntp"
version = "1.0.3"
edition = "2021"
authors = ["ReK2, Hispagatos"]
description = "This is a Rust library that provides a way to interact with NNTP servers, compliant with RFC 3977 and RFC 4643."
license = "GPL-3.0-or-later"
homepage = "https://git.sr.ht/~rek2/rek2_nntp"
repository = "https://git.sr.ht/~rek2/rek2_nntp"
documentation = "https://git.sr.ht/~rek2/rek2_nntp"
keywords = ["nntp", "usenet"]
categories = ["command-line-utilities", "api-bindings", "network-programming"]

[dependencies]
native-tls = "0.2.11"
bufstream = "0.1.4"
tokio = { version = "1", features = ["full"] }
rustls = "0.21.7"
tokio-rustls = "0.24.1"
webpki = "0.21.4"
webpki-roots = "0.21.1"
tokio-native-tls = "0.3.1"
